stages:
  build_activities:
    cmd: Rscript src/1_build_activities.R
    deps:
      - src/1_build_activities.R
    outs:
      - cache/train.csv
  build_model:
    cmd: Rscript src/2_build_model.R
    deps: 
      - src/2_build_model.R
      - cache/train.csv
    outs:
      - brick/one_hot_triplet.hdf5