pacman::p_load(biobricks, arrow, tidyverse, magrittr)
# biobricks::initialize()
# brick_install("chemharmony")
# brick_pull("chemharmony")
# brick_remove("chemharmony")
# brick_repro("chemharmony")
chemharmony <- brick_load("chemharmony")
activities <- chemharmony$harmonized$activities.parquet |> collect()
head(activities)
